FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN mkdir /app
WORKDIR /app

COPY ./Donola.CV /app

RUN dotnet restore --no-cache /app/CV.DataAccessLayer/project.json
RUN dotnet restore --no-cache /app/CV.Core/project.json
RUN dotnet restore --no-cache /app/CV.Api/project.json
RUN dotnet restore --no-cache /app/CV.Core.Tests/project.json
RUN dotnet restore --no-cache /app/CV.Api.Tests/project.json

RUN dotnet build /app/**/project.json

WORKDIR /app/CV.Api

EXPOSE 5050
CMD ["dotnet", "run"]